import { useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../api';
import { FavoriteButton } from '../components/ProviderCard';
import { ErrorBox, Icon, Loading, StarInput, Stars } from '../components/ui';
import { useLocation } from '../location';
import type { ReviewSummary } from '../types';
import { useAsync } from '../useAsync';

/** AI feature 1: summary of the provider's reviews, generated by the LLM via the backend. */
function ReviewSummaryPanel({ providerId, nbAvis }: { providerId: number; nbAvis: number }) {
  const [summary, setSummary] = useState<ReviewSummary | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      setSummary(await api.aiReviewSummary(providerId));
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="card ai-summary">
      <div className="ai-head">
        <h3>
          <Icon name="auto_awesome" /> Résumé des avis par IA
        </h3>
        <button className="btn btn-small" onClick={generate} disabled={loading || nbAvis < 2}>
          {loading ? 'Analyse…' : summary ? 'Régénérer' : 'Résumer les avis'}
        </button>
      </div>
      {nbAvis < 2 && <p className="muted small">Au moins 2 avis sont nécessaires.</p>}
      {error && <ErrorBox message={error} />}
      {summary && (
        <div className="ai-body">
          <p>{summary.resume}</p>
          <div className="ai-cols">
            <div>
              <h4>Points forts</h4>
              <ul>{summary.points_forts.map((x) => <li key={x}>{x}</li>)}</ul>
            </div>
            <div>
              <h4>Points faibles</h4>
              {summary.points_faibles.length ? (
                <ul>{summary.points_faibles.map((x) => <li key={x}>{x}</li>)}</ul>
              ) : (
                <p className="muted small">Aucun point faible relevé.</p>
              )}
            </div>
          </div>
          <div className="chips">{summary.mots_cles.map((k) => <span key={k} className="chip static">{k}</span>)}</div>
          <p className="muted small">Généré par IA à partir de {summary.nb_avis} avis.</p>
        </div>
      )}
    </div>
  );
}

function ReviewForm({ providerId, onDone }: { providerId: number; onDone: () => void }) {
  const [note, setNote] = useState(0);
  const [commentaire, setCommentaire] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  async function submit(e: FormEvent) {
    e.preventDefault();
    setSaving(true);
    setError(null);
    try {
      await api.postReview(providerId, note, commentaire);
      setNote(0);
      setCommentaire('');
      onDone();
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSaving(false);
    }
  }

  return (
    <form onSubmit={submit} className="card review-form">
      <h3>Donner votre avis</h3>
      <StarInput value={note} onChange={setNote} />
      <label className="field">
        Commentaire
        <textarea
          rows={3}
          maxLength={500}
          value={commentaire}
          onChange={(e) => setCommentaire(e.target.value)}
          placeholder="Comment s’est passée l’intervention ?"
        />
      </label>
      {error && <ErrorBox message={error} />}
      <button className="btn" disabled={saving || note === 0}>
        {saving ? 'Envoi…' : 'Publier mon avis'}
      </button>
    </form>
  );
}

export function ProviderDetail() {
  const id = Number(useParams().id);
  const { lat, lng } = useLocation();
  const provider = useAsync(() => api.provider(id, lat, lng), [id, lat, lng]);
  const reviews = useAsync(() => api.reviews(id), [id]);

  function refreshAll() {
    provider.reload();
    reviews.reload();
  }

  if (provider.loading && !provider.data) return <Loading />;
  if (provider.error) return <ErrorBox message={provider.error} onRetry={provider.reload} />;
  const p = provider.data!;

  return (
    <>
      <Link to="/providers" className="back">
        <Icon name="arrow_back" /> Retour aux prestataires
      </Link>

      <div className="detail-hero card">
        {p.photo_url && <img src={p.photo_url} alt="" />}
        <div className="detail-title">
          <div className="provider-head">
            <h1>{p.nom_atelier}</h1>
            <FavoriteButton providerId={p.id} initial={p.est_favori} />
          </div>
          <div className="provider-meta">
            <Stars value={p.note_moyenne} />
            <span className="muted small">({p.nb_avis} avis)</span>
            <span className="muted small">
              <Icon name="near_me" /> {p.distance_km.toFixed(1)} km
            </span>
            <span className={`badge ${p.est_disponible ? 'ok' : 'warn'}`}>
              {p.est_disponible ? 'Disponible' : 'Complet'}
            </span>
          </div>
          <p>{p.description}</p>
        </div>
      </div>

      <div className="detail-grid">
        <div className="detail-main">
          <section className="card">
            <h2>Prestations et tarifs</h2>
            <table className="table">
              <tbody>
                {p.prestations.map((s) => (
                  <tr key={s.id}>
                    <td>
                      <strong>{s.nom}</strong>
                      <div className="muted small">
                        {s.category_nom} · {s.description} · ~{s.duree_estimee} min
                      </div>
                    </td>
                    <td className="price right">{s.prix.toFixed(0)} TND</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          <ReviewSummaryPanel providerId={p.id} nbAvis={p.nb_avis} />

          <section>
            <h2>Avis clients</h2>
            {reviews.loading && !reviews.data && <Loading />}
            {reviews.error && <ErrorBox message={reviews.error} onRetry={reviews.reload} />}
            <div className="review-list">
              {reviews.data?.map((r) => (
                <article key={r.id} className="card review">
                  <div className="review-head">
                    <strong>{r.auteur}</strong>
                    <Stars value={r.note} />
                    <span className="muted small">{new Date(r.created_at).toLocaleDateString('fr-FR')}</span>
                  </div>
                  {r.commentaire && <p>{r.commentaire}</p>}
                </article>
              ))}
              {reviews.data?.length === 0 && <p className="card empty">Aucun avis pour le moment.</p>}
            </div>
            <ReviewForm providerId={p.id} onDone={refreshAll} />
          </section>
        </div>

        <aside className="card info">
          <h3>Adresse</h3>
          <p>{p.adresse}</p>
          <h3>Horaires</h3>
          <dl className="hours">
            {Object.entries(p.horaires).map(([day, h]) => (
              <div key={day}>
                <dt>{day}</dt>
                <dd>{h}</dd>
              </div>
            ))}
          </dl>
        </aside>
      </div>
    </>
  );
}
